### ISSUE TITLE
api v1 : Product

### ISSUE THREAD

**Issue by easa** [DevTeam125/shopping-website#2]
# Product story (api)

the project is about a general shop  
the base entities are:
- product
- comment
- user
- shopping basket 
there is an API endpoint equivalent to each of these entities

## brief product version schema
```typescript
type Product = {
  id: string;
  name: string;
  price: price;
  status: status;
  rating: number;
  photo: {
    title: string;
    url: string;
  }
}
```

## full product version schema
```typescript
type Product = {
  id: string;
  name: string;
  price: price;
  status: status;
  rating: number;
  description: string;
  photos: Array<{
    title: string;
    url: string;
  }>;
  features: Array<{
    title: string;
    description: string;
  }>;
}
```

## examples

given a API call using curl
when the call is like `HTTP get localhost/product`
then the result is a list of products (brief product version)

given a API call using curl
when the call is like `HTTP get localhost/product/:productId`
then the result is a single product item in json (full product version)

given a API call using curl
when the call is like `HTTP post localhost/product` and the body is a json of type product without any id field
then the new product should be available in `get localhost/product/` and `get localhost/product/:productId`

given a API call using curl
when the call is like `HTTP put localhost/product` and the body is a json of type product with an id
then the edited product should be available in `get localhost/product/` and `get localhost/product/:productId`

given a API call using curl
when the call is like `HTTP delete localhost/product/:productId`
then the deleted product should not be seen in `get localhost/product/` nor `get localhost/product/:productId`

**Comment by DevTeam125** [comment]
Shouldn't the auth part get done first?
e.g.
POST localhost/users/login, (username and password as json payload to be sent)
    Result: Bearer <TOKEN> (JWT token)
Also user CRUD stuffs like creating, updating, changing password, etc

**Comment by easa** [comment]
Let's first make the resources, then add auth as an other feature

**Comment by DevTeam125** [comment]
Completed the product entity
